### ISSUE TITLE
Consistent naming of Note and Occurrence kinds

### ISSUE THREAD

**Issue by furuholm** [grafeas/grafeas#82]
Two of the Note kinds are postfixed "Type" (VulnerabilityType and BuildType) but not the rest of them and three of the Occurence kinds are postfixed "Details" (CustomDetails, VulnerabilityDetails and BuildDetails) but not the rest of them.

I think this should be made consistent while the API is considered unstable. I don't think Type is great, but I am fine with no postfix, Details or something else (I would however rather use Type than not fixing it).

**Comment by R2wenD2** [comment]
This shouldn't be too difficult of a fix - and I'm supportive.
For notes, I'd be fine with just using the camel case name for the Type (here: https://github.com/Grafeas/Grafeas/blob/aae00b1f1853d8a253f98380c0232030f08d82eb/v1alpha1/proto/grafeas.proto#L642)

And for Occurrences, I like the details postfix because its giving details of a specific thing everywhere. 

But I'm also fine with using Details for both notes and occurrences.

I'm still working on grpc clients, but if I finish up there and you haven't sent an update I'll do this next.

**Comment by furuholm** [comment]
Great! I have no strong opinions on where to use details or not so do what you think works best.

**Comment by vtsao** [comment]
I'm in favor of consistent details suffix as well.

**Comment by furuholm** [comment]
This seems to have been resolved in v1beta1 (see https://github.com/grafeas/grafeas/blob/master/v1beta1/proto/grafeas.proto). If you agree @R2wenD2 I will go ahead and close this issue.

**Comment by vtsao** [comment]
Yup, we fixed this in v1beta1. Closing.
