### ISSUE TITLE
Is the current code buildable and functional?

### ISSUE THREAD

**Issue by doomsbuster** [Grafeas/Grafeas#90]

**Comment by doomsbuster** [comment]
I have been reading up on Grafeas, I understand that because its relatively new technology, the documentation, API spec and build process is yet to be produced. I had few questions
1. is there a database for storage of the data or is it all in memory at this point?
2. The go-server only has the storage interface, how to start this application and API server?
Are there other internal instructions that you could point to, which we can use to try out the product?

I dont have ability to edit labels else i would have labeled it "Discussion".

**Comment by furuholm** [comment]
You are correct in that the codebase is under development but it does work.

1. Persistent storage is not in place but on its way. See #84. I have [implemented support for Postgres](https://github.com/combient/Grafeas/tree/postgres-storage) and will submit this as a PR in the next couple of days or so.
2. To start the server go to `samples/server/go-server/api/server/main` and execute `go run main.go`.

The current version uses a self signed certificate, so if you want to try the interface with curl you need to add -k. This will hopefully soon be addressed as well so that users can configure their own certificates or allow insecure connections.

**Comment by doomsbuster** [comment]
Thanks for the quick response. I'll give it a try. So are you guys planning to ship this with a user interface with monitoring, dashboarding and visuals or just the API's and it would be up to the customers to determine how they want to consume the data?

**Comment by R2wenD2** [comment]
We're focused on the design/implementation and correctness of the API specification for the near to medium term, so currently no plans to create visuals/monitoring on top of that. 

cc: @justinbeckwith

**Comment by R2wenD2** [comment]
This isn't actually an issue for the project. I'm going to close this. Please use our group mailing lists for this type of discussion.
- Developer list for contributors: https://groups.google.com/forum/#!forum/grafeas-dev
- User list for user questions/feedback: https://groups.google.com/forum/#!forum/grafeas-users
